version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: pectocms-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py load_data &&
      python manage.py runserver 0.0.0.0:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
    container_name: pectocms-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
