# Generated by Django 4.2.17 on 2025-01-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_first_lang', models.CharField(max_length=255)),
                ('sentence_first_lang', models.TextField(blank=True, null=True)),
                ('word_second_lang', models.CharField(max_length=255)),
                ('sentence_second_lang', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
